kind: Service
apiVersion: v1
metadata:
  name: iemdb-back-service
  labels:
    app: iemdb-back-service
spec:
  type: NodePort
  selector:
    app: iemdb-backend
  ports:
    - port: 8080
      nodePort: 31099
      targetPort: 8080
